###
GET http://localhost:3000/messages

###

GET http://localhost:3000/friends

###

GET http://localhost:3000/friends/1

###

POST http://localhost:3000/friends
Content-Type: application/json

{
    "name": "Bruno"
}

